FROM microsoft/windowsservercore

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_SHA256 3AB1286E8FDADC60F57A97F2222AD6B3D7A48847A52EF812CC8D5F354BF500FF

RUN powershell -Command \
    wget -Uri https://nodejs.org/dist/v6.10.3/node-v6.10.3-x64.msi -Outfile node.msi -UseBasicParsing; \
    if ((Get-FileHash node.msi -Algorithm sha256).Hash -ne $env:NODE_SHA256) {exit 1}; \
    Start-Process -FilePath msiexec -ArgumentList /q, /i, node.msi -Wait; \
    Remove-Item -Path node.msi

CMD ["node.exe"]
